name: shipping
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get: ^4.6.5
dev_dependencies:
  font_awesome_flutter: ^10.1.0
  sqflite: ^2.0.0
  intl: ^0.19.0
  provider: ^6.1.2
  path_provider: ^2.0.11
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.0.3
  flutter_secure_storage: ^8.0.0
  permission_handler: ^10.2.0
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/images/

